export const dummyData = [
  {
    id: 1,
    businessName: "Kesavan",
    clientId: 75123,
    email: "kesavan@inc.com",
    contactNumber: 8075423337,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 2,
    action: "Copy",
  },
  {
    id: 2,
    businessName: "Akash",
    clientId: 75124,
    email: "	akash@inc.com",
    contactNumber: 9629653377,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 5,
    action: "Copy",
  },
  {
    id: 3,
    businessName: "Naveen Kumar",
    clientId: 75125,
    email: "	naveen@inc.com",
    contactNumber: 902965723,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 0,
    action: "Copy",
  },
  {
    id: 4,
    businessName: "Arun Prakash",
    clientId: 75126,
    email: "arun@inc.com",
    contactNumber: 9945687219,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 3,
    action: "Copy",
  },
  {
    id: 5,
    businessName: "Manoj",
    clientId: 75127,
    email: "manoj@inc.com",
    contactNumber: 9956231245,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 2,
    action: "Copy",
  },
  {
    id: 6,
    businessName: "Vishnu",
    clientId: 75128,
    email: "vishnu@inc.com",
    contactNumber: 9366144319,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 1,
    action: "Copy",
  },
  {
    id: 7,
    businessName: "Varun",
    clientId: 75129,
    email: "varun@inc.com",
    contactNumber: 9098644319,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 6,
    action: "Copy",
  },
  {
    id: 8,
    businessName: "Raj",
    clientId: 75130,
    email: "raj@inc.com",
    contactNumber: 9956238472,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 3,
    action: "Copy",
  },
  {
    id: 9,
    businessName: "Guru",
    clientId: 75131,
    email: "guru@inc.com",
    contactNumber: 9875461320,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 0,
    action: "Copy",
  },
  {
    id: 10,
    businessName: "Gowtham",
    clientId: 75132,
    email: "gowtham@inc.com",
    contactNumber: 9078654219,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 7,
    action: "Copy",
  },
  {
    id: 11,
    businessName: "Vijay",
    clientId: 75133,
    email: "Vijay@inc.com",
    contactNumber: 9944421563,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 3,
    action: "Copy",
  },
  {
    id: 12,
    businessName: "Ilango",
    clientId: 75134,
    email: "Ilango@23.com",
    contactNumber: 9978423105,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 2,
    action: "Copy",
  },
  {
    id: 13,
    businessName: "Sam",
    clientId: 75136,
    email: "samoff@w.com",
    contactNumber: 6396857412,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 3,
    action: "Copy",
  },
  {
    id: 14,
    businessName: "Dinesh",
    clientId: 75137,
    email: "dine24@.com",
    contactNumber: 9023105648,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 6,
    action: "Copy",
  },
  {
    id: 15,
    businessName: "Chakravarthy",
    clientId: 75138,
    email: "akv@90.com",
    contactNumber: 9889564219,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 2,
    action: "Copy",
  },
  {
    id: 16,
    businessName: "Prerna",
    clientId: 75139,
    email: "prernaof@inc.com",
    contactNumber: 9876543210,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 8,
    action: "Copy",
  },
  {
    id: 17,
    businessName: "Irin",
    clientId: 75140,
    email: "iamIrin@inc.com",
    contactNumber: 9845321670,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 4,
    action: "Copy",
  },

  {
    id: 18,
    businessName: "Joyal",
    clientId: 75141,
    email: "jo77@.com",
    contactNumber: 9012795436,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 2,
    action: "Copy",
  },
  {
    id: 19,
    businessName: "Mohamad",
    clientId: 75142,
    email: "mohaMD202@.com",
    contactNumber: 9820346858,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 3,
    action: "Copy",
  },
  {
    id: 20,
    businessName: "Praveen",
    clientId: 75143,
    email: "praveen@.com",
    contactNumber: 6345128796,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 3,
    action: "Copy",
  },
  {
    id: 21,
    businessName: "Nandha Kumar",
    clientId: 75144,
    email: "nkOfficial@.com",
    contactNumber: 7386459213,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 1,
    action: "Copy",
  },
  {
    id: 22,
    businessName: "Mani",
    clientId: 75145,
    email: "mani@gmail.com",
    contactNumber: 9043513609,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 0,
    action: "Copy",
  },
  {
    id: 23,
    businessName: "Harish",
    clientId: 75146,
    email: "hari12@.com",
    contactNumber: 6321302306,
    netTerms: "-",
    terminationNotice: "-",
    status: "Active",
    category: "-",
    additionalInfo: "-",
    activePlacements: 5,
    action: "Copy",
  },
  {
    id: 24,
    businessName: "Vasudev Menon",
    clientId: 75147,
    email: "VasuM7@.com",
    contactNumber: 7300886612,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 3,
    action: "Copy",
  },
  {
    id: 25,
    businessName: "Salmon",
    clientId: 75147,
    email: "salmonS@gmail.com",
    contactNumber: 9923105764,
    netTerms: "-",
    terminationNotice: "-",
    status: "Inactive",
    category: "-",
    additionalInfo: "-",
    activePlacements: 2,
    action: "Copy",
  },
];
