import { RiDeleteBin6Line } from "react-icons/ri";
import { IoMdContact } from "react-icons/io";

export const Developers = [
  {
    "Business Name": "ULTEUS",
    "Client Id": 95765827,
    Email: "lgillilandi@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "OYSTEL",
    "Client Id": 90783245,
    Email: "pmuirdenc@posterous.com",
    "Contact Number": "191-724-8236",
    "Net Terms": "Gb Fabrication",
    "Termination Name": "Common contracts with termination clauses:",
    Status: "DeActive",
    Category: "Management Information System",
    "Additional Info": "-",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "JUURO",
    "Client Id": 87346216,
    Email: "babthorpe6@cnn.com",
    "Contact Number": "672-745-9039",
    "Net Terms": "Term Bikes",
    "Termination Name": "Termission clause exples",
    Status: "DeActive",
    Category: "Decision Support System",
    "Additional Info": "-",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "OQTOS",
    "Client Id": 47342109,
    Email: "bballham3@alibaba.com",
    "Contact Number": "515-637-0898",
    "Net Terms": "Go Materials",
    "Termination Name": "Purpose of Termination Clause Expless",
    Status: "Active",
    Category: "Office Automation System",
    "Additional Info": "-",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "ALPEVO",
    "Client Id": 53248075,
    Email: "drustman2@microsoft.com",
    "Contact Number": "968-101-1164",
    "Net Terms": "SDI Fire",
    "Termination Name": "Termination clause explained",
    Status: "Active",
    Category: "Transaction Processing System",
    "Additional Info": "-",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "SPA PARAGON",
    "Client Id": 34890912,
    Email: "rwilne1@cbsnews.com",
    "Contact Number": "895-727-7836",
    "Net Terms": "Trenchless Supply",
    "Termination Name": "Termination Clause Defined",
    Status: "Active",
    Category: "Executive Support Team",
    "Additional Info": "-",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "GAME DAY CATERING",
    "Client Id": 95765827,
    Email: "gamedaycatering@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "DeActive",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "EXPOLARATION KIDS",
    "Client Id": 96087321,
    Email: "expolarationkids@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "DeActive",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "YOGA PROFESSOR",
    "Client Id": 29087455,
    Email: "yogaprofessor@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "DARVIN TRAVEL",
    "Client Id": 93450729,
    Email: "darvintravel@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "PARTY PLEX",
    "Client Id": 24536789,
    Email: "partyplex@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "PIZZA FACTOR",
    "Client Id": 34567902,
    Email: "pizzafactor@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "ACRON CRAFTS",
    "Client Id": 23098458,
    Email: "acroncrafts@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "DeActive",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "GROUPON",
    "Client Id": 87569034,
    Email: "groupon@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "INFLUITIVE",
    "Client Id": 95098923,
    Email: "influitive@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "DeActive",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "SPIN FLUENCE",
    "Client Id": 54367810,
    Email: "spinfluence@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "DeActive",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "INTELLEVISION",
    "Client Id": 12546780,
    Email: "intellevision@un.org",
    "Contact Number": "188-572-5106",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "PERFICIENT",
    "Client Id": 32545780,
    Email: "perficient@un.org",
    "Contact Number": "080-26599990",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "DeActive",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "OMNILERT",
    "Client Id": 12098765,
    Email: "omnilert@un.org",
    "Contact Number": "1800 425 3800",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "TECHNOLOGENT",
    "Client Id": 76098234,
    Email: "technologent@un.org",
    "Contact Number": "1800 11 2211",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "SECURITEAM",
    "Client Id": 90763451,
    Email: "securiteam@un.org",
    "Contact Number": "+91 22 40919191",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "PERCEPTA",
    "Client Id": 80987459,
    Email: "percepta@un.org",
    "Contact Number": "1800 220 088",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "EXELA MOVERS",
    "Client Id": 87980745,
    Email: "exelamovers@un.org",
    "Contact Number": "(022) 40426005",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "IBOTTA",
    "Client Id": 95765827,
    Email: "ibotta@un.org",
    "Contact Number": "(044) 39113784",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "WANDARU",
    "Client Id": 90345621,
    Email: "wandaru@un.org",
    "Contact Number": "(044) 71721112",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "ACEABLE",
    "Client Id": 93214569,
    Email: "aceable@un.org",
    "Contact Number": " (022) 40429123",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "INTREPID TRAVEL",
    "Client Id": 90345678,
    Email: "intrepidtravel@un.org",
    "Contact Number": "(022)40429127",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "DEFENDIFY",
    "Client Id": 98432345,
    Email: "defendify@un.org",
    "Contact Number": "1800 425 1112",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "DeActive",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "TWISTERS GYMNASTICS ACADEMY",
    "Client Id": 70234589,
    Email: "twistersgymnastics@un.org",
    "Contact Number": " (022)40429036",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "AIMS COMMUNITY COLLEGE",
    "Client Id": 80231573,
    Email: "aimscommunity@un.org",
    "Contact Number": "(080)69999203",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "KABOOM FIREWORKS",
    "Client Id": 94231072,
    Email: "kaboomfireworks@un.org",
    "Contact Number": "1800 220 088",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "COMPOSS MORTAGE",
    "Client Id": 90856423,
    Email: "compossmortage@un.org",
    "Contact Number": "(022) – 40919191",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "DeActive",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "MARATHON PHYSICAL THEROPHY",
    "Client Id": 96542102,
    Email: "marathonphysical@un.org",
    "Contact Number": "1800 103 1906 ",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "DeActive",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
  {
    "Business Name": "SEMICOLON BOOKSTORE",
    "Client Id": 90876542,
    Email: "semincolon@un.org",
    "Contact Number": "1800 220 229 ",
    "Net Terms": "Archipelago Lighting",
    "Termination Name": "Termission Clause FAQ's",
    Status: "Active",
    Category: "Knowledge Work System",
    "Additional Info": "_",
    "Active placements": <IoMdContact />,
    Actions: <RiDeleteBin6Line />,
  },
];
